name: Python app with Github actions

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    # Ensure the default working directory is set correctly
    defaults:
      run:
        working-directory: C:\Users\Administrator\scaffold

    steps:
      # Checkout repository into the correct directory
      - name: Checkout repository to correct directory
        uses: actions/checkout@v4
        with:
          path: C:\Users\Administrator\scaffold

      # Print the current directory to verify it
      - name: Print Current Directory
        run: pwd
        shell: pwsh

      # List files in the current directory to confirm correct files are there
      - name: List Files
        run: ls -l
        shell: pwsh

      # Install dependencies using the Makefile
      - name: Install dependencies
        run: make install
        shell: pwsh

      # Run linting with pylint
      - name: Lint with pylint
        run: make lint
        shell: pwsh

      # Run tests with pytest
      - name: Test with pytest
        run: make test
        shell: pwsh

      # Format code with python black
      - name: Format code with python black
        run: make format
        shell: pwsh
